name: my_coffy_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  flutter_native_splash: ^2.4.1
  sqflite: ^2.4.1
  path: ^1.9.0
  share_plus: ^10.1.2
  flutter_email_sender: ^6.0.3
  camera: ^0.11.0+2
  path_provider: ^2.0.9
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.9
  flutter_launcher_icons: 0.14.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_rating_bar: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  remove_alpha_ios: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/image/coffe_image.png
    - assets/image/logo.png
    - assets/recetas.json
    - assets/preguntas.json

